### ISSUE TITLE
Docker Image published on docker hub under 'gbifs' user

### ISSUE THREAD

**Issue by godfoder** [gbif/docker-ipt#1]
There are two users for GBIF on docker hub:

https://hub.docker.com/r/gbif/
https://hub.docker.com/r/gbifs/

and this image is currently registered under gbifs. I found this out when I tried to do the pull/run workflow using the names in the README file and it didn't work. I would either update the readme file or, preferably, migrate the image over to the gbif user.

P.S. Good job on this, I was just about to sit down and dockerize IPT myself. You beat me by 13 days :)

**Comment by mdoering** [comment]
Oh. I wasn't aware of the other one, strange that I missed it. Ill figure out the owner and will try to move the images, thanks!

**Comment by mdoering** [comment]
we use https://hub.docker.com/r/gbif/ now, gbifs is deprecated but we cannot find a way to remove it. Even after getting in touch with the docker team
