### ISSUE TITLE
Instructions to run the docker ipt

### ISSUE THREAD

**Issue by ainsofs** [gbif/docker-ipt#3]
Hi,
I need some help running the IPT using docker. I've downloaded the image and run the following command:

docker run -d -P gbif/ipt

But how do I access the IPT interface? I've tried going to http://{docker_ip} port 8000 and port 8080 but nothing is showing up

Appreciate any help.

Cheers,

**Comment by mdoering** [comment]
Hi, indeed the ports are not exposed as expected that way.
Please run the image mapping port 8080 explicitly:

`docker run -d -p 8080:8080 gbif/ipt`

I am also just now pushing the just released version 2.3.5 to docker hub if you wanna grab that version with more security patches against XSS
